---
- name: EC2 인스턴스 작성
  ec2:
    image: "{{ ami_image }}"
    instance_type: "{{ instance_type }}"
    region: ap-northeast-1
    key_name: "{{ key_name }}"
    group: "{{ group_name }}"
    instance_tags:
      Name: "{{ group_name }}"
    wait: yes
    wait_timeout: 300
    volumes:
      - device_name: "{{ device_name }}"
        device_type: "{{ device_type }}"
        volume_size: "{{ volume_size }}"
        delete_on_termination: yes
  register: ec2
